# Generated by Django 6.0.4 on 2026-04-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('course', models.CharField(max_length=50)),
                ('marks', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='students',
        ),
    ]
